tasks:
  - command: LAMA_PORT=8000 ./lama.sh
  - command: LAMA_PORT=8001 ./lama.sh
  - command: LAMA_PORT=8002 ./lama.sh
  - command: LAMA_PORT=8003 ./lama.sh
  - command: LAMA_PORT=8004 ./lama.sh
  - command: LAMA_PORT=8005 ./lama.sh
  - command: LAMA_PORT=8006 ./lama.sh
  - command: LAMA_PORT=8007 ./lama.sh
  - command: LAMA_PORT=8008 ./lama.sh
  - command: LAMA_PORT=8009 ./lama.sh
  - command: LAMA_PORT=8010 ./lama.sh
  - command: LAMA_PORT=8011 ./lama.sh
  - command: LAMA_PORT=8012 ./lama.sh
  - command: LAMA_PORT=8013 ./lama.sh
  - command: LAMA_PORT=8014 ./lama.sh
  - command: LAMA_PORT=8015 ./lama.sh
  - command: LAMA_PORT=8016 ./lama.sh
  - command: LAMA_PORT=8017 ./lama.sh
  - command: LAMA_PORT=8018 ./lama.sh
  - command: LAMA_PORT=8019 ./lama.sh
  - command: LAMA_PORT=8020 ./lama.sh
  - command: LAMA_PORT=8021 ./lama.sh
  - command: LAMA_PORT=8022 ./lama.sh
  - command: LAMA_PORT=8023 ./lama.sh
  - command: LAMA_PORT=8024 ./lama.sh
  - command: LAMA_PORT=8025 ./lama.sh
  - command: LAMA_PORT=8026 ./lama.sh
  - command: LAMA_PORT=8027 ./lama.sh
  - command: LAMA_PORT=8028 ./lama.sh
  - command: LAMA_PORT=8029 ./lama.sh
  - command: LAMA_PORT=8030 ./lama.sh
  - command: LAMA_PORT=8031 ./lama.sh
  - command: LAMA_PORT=8032 ./lama.sh
  - command: LAMA_PORT=8033 ./lama.sh
  - command: LAMA_PORT=8034 ./lama.sh
  - command: LAMA_PORT=8035 ./lama.sh
  - command: LAMA_PORT=8036 ./lama.sh
  - command: LAMA_PORT=8037 ./lama.sh
  - command: LAMA_PORT=8038 ./lama.sh
  - command: LAMA_PORT=8039 ./lama.sh
  - command: LAMA_PORT=8040 ./lama.sh
  - command: LAMA_PORT=8041 ./lama.sh
  - command: LAMA_PORT=8042 ./lama.sh
  - command: LAMA_PORT=8043 ./lama.sh
  - command: LAMA_PORT=8044 ./lama.sh
  - command: LAMA_PORT=8045 ./lama.sh
  - command: LAMA_PORT=8046 ./lama.sh
  - command: LAMA_PORT=8047 ./lama.sh
  - command: LAMA_PORT=8048 ./lama.sh
  - command: LAMA_PORT=8049 ./lama.sh
  - command: LAMA_PORT=8050 ./lama.sh
  - command: LAMA_PORT=8051 ./lama.sh
  - command: LAMA_PORT=8052 ./lama.sh
  - command: LAMA_PORT=8053 ./lama.sh
  - command: LAMA_PORT=8054 ./lama.sh
  - command: LAMA_PORT=8055 ./lama.sh
  - command: LAMA_PORT=8056 ./lama.sh
  - command: LAMA_PORT=8057 ./lama.sh
  - command: LAMA_PORT=8058 ./lama.sh
  - command: LAMA_PORT=8059 ./lama.sh
  - command: LAMA_PORT=8060 ./lama.sh
  - command: LAMA_PORT=8061 ./lama.sh
  - command: LAMA_PORT=8062 ./lama.sh
  - command: LAMA_PORT=8063 ./lama.sh
  - command: LAMA_PORT=8064 ./lama.sh
  - command: LAMA_PORT=8065 ./lama.sh
  - command: LAMA_PORT=8066 ./lama.sh
  - command: LAMA_PORT=8067 ./lama.sh
  - command: LAMA_PORT=8068 ./lama.sh
  - command: LAMA_PORT=8069 ./lama.sh
  - command: LAMA_PORT=8070 ./lama.sh
  - command: LAMA_PORT=8071 ./lama.sh
  - command: LAMA_PORT=8072 ./lama.sh
  - command: LAMA_PORT=8073 ./lama.sh
  - command: LAMA_PORT=8074 ./lama.sh
  - command: LAMA_PORT=8075 ./lama.sh
  - command: LAMA_PORT=8076 ./lama.sh
  - command: LAMA_PORT=8077 ./lama.sh
  - command: LAMA_PORT=8078 ./lama.sh
  - command: LAMA_PORT=8079 ./lama.sh
  - command: LAMA_PORT=8080 ./lama.sh
  - command: LAMA_PORT=8081 ./lama.sh
  - command: LAMA_PORT=8082 ./lama.sh
  - command: LAMA_PORT=8083 ./lama.sh
  - command: LAMA_PORT=8084 ./lama.sh
  - command: LAMA_PORT=8085 ./lama.sh
  - command: LAMA_PORT=8086 ./lama.sh
  - command: LAMA_PORT=8087 ./lama.sh
  - command: LAMA_PORT=8088 ./lama.sh
  - command: LAMA_PORT=8089 ./lama.sh
  - command: LAMA_PORT=8090 ./lama.sh
  - command: LAMA_PORT=8091 ./lama.sh
  - command: LAMA_PORT=8092 ./lama.sh
  - command: LAMA_PORT=8093 ./lama.sh
  - command: LAMA_PORT=8094 ./lama.sh
  - command: LAMA_PORT=8095 ./lama.sh
  - command: LAMA_PORT=8096 ./lama.sh
  - command: LAMA_PORT=8097 ./lama.sh
  - command: LAMA_PORT=8098 ./lama.sh
  - command: LAMA_PORT=8099 ./lama.sh
  - command: LAMA_PORT=8100 ./lama.sh
  - command: LAMA_PORT=8101 ./lama.sh
  - command: LAMA_PORT=8102 ./lama.sh
  - command: LAMA_PORT=8103 ./lama.sh
  - command: LAMA_PORT=8104 ./lama.sh
  - command: LAMA_PORT=8105 ./lama.sh
  - command: LAMA_PORT=8106 ./lama.sh
  - command: LAMA_PORT=8107 ./lama.sh
  - command: LAMA_PORT=8108 ./lama.sh
  - command: LAMA_PORT=8109 ./lama.sh
  - command: LAMA_PORT=8110 ./lama.sh
  - command: LAMA_PORT=8111 ./lama.sh
  - command: LAMA_PORT=8112 ./lama.sh
  - command: LAMA_PORT=8113 ./lama.sh
  - command: LAMA_PORT=8114 ./lama.sh
  - command: LAMA_PORT=8115 ./lama.sh
  - command: LAMA_PORT=8116 ./lama.sh
  - command: LAMA_PORT=8117 ./lama.sh
  - command: LAMA_PORT=8118 ./lama.sh
  - command: LAMA_PORT=8119 ./lama.sh
  - command: LAMA_PORT=8120 ./lama.sh
  - command: LAMA_PORT=8121 ./lama.sh
  - command: LAMA_PORT=8122 ./lama.sh
