ports:
  - port: 7000
  - port: 7001
  - port: 7002
  - port: 7003
  - port: 8000
    visibility: public
    onOpen: open-preview
  - port: 8001
    onOpen: open-browser
tasks:
  - command: SERVER_PORT=8000 node server.js
  - command: SERVER_PORT=8001 node server.js
  - command: SERVER_PORT=8002 node server.js
  - command: SERVER_PORT=8003 node server.js
  - command: SERVER_PORT=8004 node server.js
  - command: SERVER_PORT=8005 node server.js
  - command: SERVER_PORT=8006 node server.js
  - command: SERVER_PORT=8007 node server.js
  - command: SERVER_PORT=8008 node server.js
  - command: SERVER_PORT=8009 node server.js
  - command: SERVER_PORT=8010 node server.js
  - command: SERVER_PORT=8011 node server.js
  - command: SERVER_PORT=8012 node server.js
  - command: SERVER_PORT=8013 node server.js
  - command: SERVER_PORT=8014 node server.js
  - command: SERVER_PORT=8015 node server.js
  - command: SERVER_PORT=8016 node server.js
  - command: SERVER_PORT=8017 node server.js
  - command: SERVER_PORT=8018 node server.js
  - command: SERVER_PORT=8019 node server.js
  - command: SERVER_PORT=8020 node server.js
  - command: SERVER_PORT=8021 node server.js
  - command: SERVER_PORT=8022 node server.js
  - command: SERVER_PORT=8023 node server.js
  - command: SERVER_PORT=8024 node server.js
  - command: SERVER_PORT=8025 node server.js
  - command: SERVER_PORT=8026 node server.js
  - command: SERVER_PORT=8027 node server.js
  - command: SERVER_PORT=8028 node server.js
  - command: SERVER_PORT=8029 node server.js
  - command: SERVER_PORT=8030 node server.js
  - command: SERVER_PORT=8031 node server.js
  - command: SERVER_PORT=8032 node server.js
  - command: SERVER_PORT=8033 node server.js
  - command: SERVER_PORT=8034 node server.js
  - command: SERVER_PORT=8035 node server.js
  - command: SERVER_PORT=8036 node server.js
  - command: SERVER_PORT=8037 node server.js
  - command: SERVER_PORT=8038 node server.js
  - command: SERVER_PORT=8039 node server.js
  - command: SERVER_PORT=8040 node server.js
  - command: SERVER_PORT=8041 node server.js
  - command: SERVER_PORT=8042 node server.js
  - command: SERVER_PORT=8043 node server.js
  - command: SERVER_PORT=8044 node server.js
  - command: SERVER_PORT=8045 node server.js
  - command: SERVER_PORT=8046 node server.js
  - command: SERVER_PORT=8047 node server.js
  - command: SERVER_PORT=8048 node server.js
  - command: SERVER_PORT=8049 node server.js
  - command: SERVER_PORT=8050 node server.js
  - command: SERVER_PORT=8051 node server.js
  - command: SERVER_PORT=8052 node server.js
  - command: SERVER_PORT=8053 node server.js
  - command: SERVER_PORT=8054 node server.js
  - command: SERVER_PORT=8055 node server.js
  - command: SERVER_PORT=8056 node server.js
  - command: SERVER_PORT=8057 node server.js
  - command: SERVER_PORT=8058 node server.js
  - command: SERVER_PORT=8059 node server.js
  - command: SERVER_PORT=8060 node server.js
  - command: SERVER_PORT=8061 node server.js
  - command: SERVER_PORT=8062 node server.js
  - command: SERVER_PORT=8063 node server.js
  - command: SERVER_PORT=8064 node server.js
  - command: SERVER_PORT=8065 node server.js
  - command: SERVER_PORT=8066 node server.js
  - command: SERVER_PORT=8067 node server.js
  - command: SERVER_PORT=8068 node server.js
  - command: SERVER_PORT=8069 node server.js
  - command: SERVER_PORT=8070 node server.js
  - command: SERVER_PORT=8071 node server.js
  - command: SERVER_PORT=8072 node server.js
  - command: SERVER_PORT=8073 node server.js
  - command: SERVER_PORT=8074 node server.js
  - command: SERVER_PORT=8075 node server.js
  - command: SERVER_PORT=8076 node server.js
  - command: SERVER_PORT=8077 node server.js
  - command: SERVER_PORT=8078 node server.js
  - command: SERVER_PORT=8079 node server.js
  - command: SERVER_PORT=8080 node server.js
  - command: SERVER_PORT=8081 node server.js
  - command: SERVER_PORT=8082 node server.js
  - command: SERVER_PORT=8083 node server.js
  - command: SERVER_PORT=8084 node server.js
  - command: SERVER_PORT=8085 node server.js
  - command: SERVER_PORT=8086 node server.js
  - command: SERVER_PORT=8087 node server.js
  - command: SERVER_PORT=8088 node server.js
  - command: SERVER_PORT=8089 node server.js
  - command: SERVER_PORT=8090 node server.js
  - command: SERVER_PORT=8091 node server.js
  - command: SERVER_PORT=8092 node server.js
  - command: SERVER_PORT=8093 node server.js
  - command: SERVER_PORT=8094 node server.js
  - command: SERVER_PORT=8095 node server.js
  - command: SERVER_PORT=8096 node server.js
  - command: SERVER_PORT=8097 node server.js
  - command: SERVER_PORT=8098 node server.js
  - command: SERVER_PORT=8099 node server.js
  - command: SERVER_PORT=8100 node server.js
  - command: SERVER_PORT=8101 node server.js
  - command: SERVER_PORT=8102 node server.js
  - command: SERVER_PORT=8103 node server.js
  - command: SERVER_PORT=8104 node server.js
  - command: SERVER_PORT=8105 node server.js
  - command: SERVER_PORT=8106 node server.js
  - command: SERVER_PORT=8107 node server.js
  - command: SERVER_PORT=8108 node server.js
  - command: SERVER_PORT=8109 node server.js
  - command: SERVER_PORT=8110 node server.js
  - command: SERVER_PORT=8111 node server.js
  - command: SERVER_PORT=8112 node server.js
  - command: SERVER_PORT=8113 node server.js
  - command: SERVER_PORT=8114 node server.js
  - command: SERVER_PORT=8115 node server.js
  - command: SERVER_PORT=8116 node server.js
  - command: SERVER_PORT=8117 node server.js
  - command: SERVER_PORT=8118 node server.js
  - command: SERVER_PORT=8119 node server.js
  - command: SERVER_PORT=8120 node server.js
  - command: SERVER_PORT=8121 node server.js
  - command: SERVER_PORT=8122 node server.js
