name: Trigger Image Prebuild

on:
  push:
    branches:
      - prebuild/image-build
  workflow_dispatch:

jobs:
  update-prebuild:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: prebuild/image-build
    - name: Append Date to prebuild.sh
      run: |
        echo "$(date)" >> prebuild.sh

    - name: Commit and Push
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add prebuild.sh
        git commit -m "Update prebuild.sh with current date and time"
        git push origin prebuild/image-build
